env:
  browser: true
  es6: true
  jasmine: true
  node: true

plugins:
  - prettier
  - jsdoc

extends:
  "eslint:recommended"

globals:
  $: true
  _: true
  adapter: true
  amplify: true
  cryptobox: true
  CryptoJS: true
  dcodeIO: true
  Dexie: true
  entities: true
  hljs: true
  jQuery: true
  keyboardJS: true
  ko: true
  libsodium: true
  linkify: true
  linkifyHtml: true
  lorem_ipsum: true
  LRUCache: true
  marked: true
  moment: true
  OpenGraphMocks: true
  pako: true
  payload: true
  PhoneFormat: true
  platform: true
  poster: true
  Proteus: true
  Raygun: true
  sinon: true
  sodium: true
  TestFactory: true
  twttr: true
  UUID: true
  wire: true
  z: true
  zeta: true

rules:
  constructor-super: 2
  default-case: 2
  func-call-spacing: 2
  handle-callback-err: 2
  id-length: [2, {exceptions: ['z']}]
  indent: [2, 2, {SwitchCase: 1}]
  jsdoc/require-hyphen-before-param-description: 2
  key-spacing: 2
  keyword-spacing: 2
  no-console: 0
  no-const-assign: 2
  no-dupe-class-members: 2
  no-else-return: 2
  no-lonely-if: 2
  no-multi-spaces: 2
  no-multiple-empty-lines: [2, {max: 2, maxBOF: 0, maxEOF: 0}]
  no-shadow: 2
  no-unused-expressions: 2
  no-unused-vars: [2, {args: none}]
  no-var: 2
  no-whitespace-before-property: 2
  prefer-const: 2
  prefer-promise-reject-errors: 2
  prefer-spread: 2
  prefer-template: 2
  prettier/prettier: [2, {
      singleQuote: true,
      trailingComma: all,
      bracketSpacing: false,
    }
  ]
  sort-keys: [2, asc, {caseSensitive: true, natural: true}]
  sort-vars: 2
  spaced-comment: [2, always, {exceptions: ["#"]}]
  strict: [2, global]
  valid-jsdoc:
    - error
    -
      prefer:
        class: class
        return: returns
      preferType:
        Boolean: boolean
        Number: number
        object: Object
        String: string
      requireParamDescription: true
      requireReturnDescription: true
